// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: query.sql

package UserDB

import (
	"context"
	"database/sql"
)

const addPassword = `-- name: AddPassword :exec
INSERT INTO passwords (UserId, Password)
VALUES
(?, ?)
`

type AddPasswordParams struct {
	Userid   sql.NullInt32
	Password string
}

func (q *Queries) AddPassword(ctx context.Context, arg AddPasswordParams) error {
	_, err := q.db.ExecContext(ctx, addPassword, arg.Userid, arg.Password)
	return err
}

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (username)
VALUES
(?)
`

func (q *Queries) CreateUser(ctx context.Context, username string) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser, username)
}
