package errors

var SUCCESS int = 0
var UNKNOWN_EXCEPTION int = 1
var UNKNOWN_PATH int = 2
var UNAUTHORIZED int32 = 3
var CANNOT_GET_AUTHORIZE_COOKIE int32 = 4
var INCORRECT_PARAM int32 = 5
var CANNOT_CONNECT_TO_BLOG_SERVICE int32 = 2004
